name: Build on release

on:
  release:
    types: [ published ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rpm-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-generate-rpm
      run: cargo install cargo-generate-rpm
    - name: Build release binary
      run: cargo build --release
    - name: Strip binary
      run: strip -s target/release/Breadboard
    - name: Generate RPM
      run: cargo generate-rpm
    - name: Upload RPM to release
      uses: softprops/action-gh-release@v2
      with:
        files: target/generate-rpm/*.rpm

  build-elf-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build release binary
      run: cargo build --release
    - name: Strip binary
      run: strip -s target/release/Breadboard
    - name: Rename binary
      run: mv target/release/Breadboard target/release/breadboard-x64
    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/breadboard-x64

  build-deb-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build release binary
      run: cargo build --release
    - name: Strip binary
      run: strip -s target/release/Breadboard
    - name: Generate DEB
      run: cargo deb
    - name: Upload DEB to release
      uses: softprops/action-gh-release@v2
      with:
        files: target/debian/*.deb

  build-deb-arm:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build release binary
      run: cargo build --release
    - name: Strip binary
      run: strip -s target/release/Breadboard
    - name: Generate DEB
      run: cargo deb
    - name: Upload DEB to release
      uses: softprops/action-gh-release@v2
      with:
        files: target/debian/*.deb

  build-elf-arm:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Build release binary
      run: cargo build --release
    - name: Strip binary
      run: strip -s target/release/Breadboard
    - name: Rename binary
      run: mv target/release/Breadboard target/release/breadboard-arm
    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/breadboard-arm

